baseURL: "https://jasonheppler.org/courses/bootcampr.2020/"
languageCode: en-us
title: "BootcampR: An Introduction to R"
theme: "kjh-tufte-hugo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - _planning$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: https://jasonheppler.org/courses/bootcampr.2020/syllabus/
      weight: 1
    - name: Schedule
      url: https://jasonheppler.org/courses/bootcampr.2020/schedule/
      weight: 2
    - name: Reference
      url: https://jasonheppler.org/courses/bootcampr.2020/reference/
      weight: 3
    - name: Code of Conduct
      url: https://jasonheppler.org/courses/bootcampr.2020/code/
      weight: 4
disableKinds: ["taxonomy", "taxonomyTerm"]      
params:
  author: Jason A. Heppler
  thumbnail: /images/unor_hex2.png
  instructor: 
    name: Jason A. Heppler
    email: jheppler@unomaha.edu
    url: "https://jasonheppler.org"
    twitter: jaheppler
    github: unolibraries/bootcampr
    office: "Criss 214"
  course:
    number:
    semester: Spring 2020
    days: "Tues"
    time: "1:30pm-3:00pm"
    location: "Criss Library"
    twitter: jaheppler
    dates: "Spring 2020"
    github: "hepplerj/bootcampr"
    copyrightYear: "2020"
    contactDetails: >-
      Office hours: By appointment.
  university: 
    name: University of Nebraska at Omaha
    url: "https://www.unomaha.edu"
  school:
    name: UNO Libraries
    url: "https://library.unomaha.edu"
  description: "Learn why and how to work with and visualize data"
  primaryColor: "#DA5B69"
  secondaryColor: "#F9983E"
  credits: >-
  logo:
    url: /images/mav_hex.png
    alt: R User Group
  meta:
    twitterSite: "@jaheppler"
    twitterCreator: "@jaheppler"
