---
title: Reference
slug: reference
output:
  blogdown::html_page:
    template: ../pandoc/toc-title_html.template
    toc: true
bibliography: ../static/bib/references.bib
csl: ../static/bib/chicago-syllabus-no-bib.csl
---

# General Motivation

-  [The Plain Person’s Guide to Plain Text Social Science](http://plain-text.co/): An overview of why you should write data-based reports using plain-text tools.

# Get Everything Installed Properly

- [Happy Git with R](https://happygitwithr.com). Read this impeccably detailed and sensible guide and do everything it says up to *at least* the end of Chapter 19. (Don't worry, the chapters are short and very clear.)
- [R Style Guide](https://style.tidyverse.org). Write readable code. 

# About Markdown and RMarkdown

- [Markdown tutorial](https://www.markdowntutorial.com/): An interactive tutorial to practice using Markdown.
- [Markdown cheatsheet](http://packetlife.net/media/library/16/Markdown.pdf): Useful one-page reminder of Markdown syntax.
- [RMarkdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf) An overview of Markdown and RMarkdown conventions.
- [RStudio Cheatsheets](https://rstudio.com/resources/cheatsheets/) Other quick guides, including a more comprehensive RMarkdown reference and a information about using RStudio's IDE, and some of the main tools in R.

# The Tools we're Using
- [R](http://r-project.org). A platform for statistical computing.
- [RStudio](http://rstudio.com). An IDE for R. The most straightforward way to use R and RMarkdown.
- [Git](http://git-scm.org). A version control system for your work. 
- [GitHub](http://github.com). Host public Git repositories for free. Pay to host private ones. Educational plans available for free. Also a source for publicly available code (e.g. R packages and utilities) written by other people.

# Extra Resources
- [Data Analysis with Dr Mike Pound](https://www.youtube.com/playlist?list=PLzH6n4zXuckpfMu_4Ff8E7Z1behQks5ba). A Computerphile YouTube series on doing data analysis with R.

# Readings

- [@battle-baptiste18:_w]
- [@berger72:_ways_seein]
- [@berinato16:_good_chart]
- [@bertin10:_semiol_graph]
- [@cairo16:_truth_art]
- [@cleveland1994]
- [@field18:_cartog]
- [@few09:_now_you_see_it]
- [@lima14:_book_trees]
- [@lupton10:_think_type]
- [@munzer14:_visual_analy_desig]
- [@tufte83:_visual_displ_quant_infor]
- [@ware08:_visual_think_desig]
- [@yau11:_visual_this]
- [@wickhamgrolemund:2017]


